#!/usr/bin/env python3
from sys import argv
import math

def factorize_numbers(file_name):
    with open(file_name) as f:
        for number in f:
            num = int(number)
            factor1 = 1  # Initialize factors
            factor2 = num  # If num is prime, it will be factored as num = num * 1
            for i in range(2, int(math.sqrt(num)) + 1):
                if num % i == 0:
                    factor1 = i
                    factor2 = num // i
                    break
            print(f"{num}={factor1}*{factor2}")

if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: python3 your_script.py <file_name>")
        exit(1)
    factorize_numbers(argv[1])
