#!/usr/bin/env python3

from sys import argv
import math

def factorize(number):
    for i in range(2, int(math.sqrt(number)) + 1):
        if number % i == 0:
            return i, number // i
    return None, None

def factorize_numbers(file_name):
    with open(file_name, 'r') as file:
        numbers = file.read().splitlines()
        for num in numbers:
            num = int(num)
            factor1, factor2 = factorize(num)
            if factor1 and factor2:
                print(f"{num}={factor1}*{factor2}")

if __name__ == "__main__":
    if len(argv) != 2:
        print("Usage: python3 your_script.py <file_name>")
        exit(1)
    file_name = argv[1]
    factorize_numbers(file_name)
