#! /usr/bin/env python3
from sys import argv

def factorize():
    # Opens the file provided as a command-line argument
    with open(argv[1]) as f:
        # Loops through each line in the file
        for number in f:
            num = int(number)  # Converts the string number to an integer
            flag = 0
            # Checks for factors from 2 to half of the number
            for i in range(2, int(num / 2) + 1, 1):
                if num % i == 0:  # Checks if 'i' is a factor of 'num'
                    # Prints the factorization in the required format
                    print("{:d}={}*{}".format(num, num // i, i))
                    flag = 1
                    break
            if flag == 0:
                # Prints the number itself as the factorization (prime number case)
                print("{:d}={}*{}".format(num, num, 1))

if __name__ == "__main__":
    factorize()  # Calls the factorize function when the script is run
